// Code generated by protoc-gen-go. DO NOT EDIT.
// source: professionService.proto

/*
Package professionService is a generated protocol buffer package.

It is generated from these files:
	professionService.proto

It has these top-level messages:
	ProfessionService
	ProfessionServiceRequest
*/
package professionService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProfessionService struct {
	Id           int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	StylistId    int32                      `protobuf:"varint,2,opt,name=stylist_id,json=stylistId" json:"stylist_id,omitempty"`
	ProfessionId int32                      `protobuf:"varint,3,opt,name=profession_id,json=professionId" json:"profession_id,omitempty"`
	ServiceId    int32                      `protobuf:"varint,4,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	IsDeleted    bool                       `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted" json:"is_deleted,omitempty"`
	UpdatedAt    *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt    *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
}

func (m *ProfessionService) Reset()                    { *m = ProfessionService{} }
func (m *ProfessionService) String() string            { return proto.CompactTextString(m) }
func (*ProfessionService) ProtoMessage()               {}
func (*ProfessionService) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProfessionService) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProfessionService) GetStylistId() int32 {
	if m != nil {
		return m.StylistId
	}
	return 0
}

func (m *ProfessionService) GetProfessionId() int32 {
	if m != nil {
		return m.ProfessionId
	}
	return 0
}

func (m *ProfessionService) GetServiceId() int32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *ProfessionService) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *ProfessionService) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ProfessionService) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ProfessionServiceRequest struct {
	StylistId int32 `protobuf:"varint,1,opt,name=stylist_id,json=stylistId" json:"stylist_id,omitempty"`
}

func (m *ProfessionServiceRequest) Reset()                    { *m = ProfessionServiceRequest{} }
func (m *ProfessionServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfessionServiceRequest) ProtoMessage()               {}
func (*ProfessionServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProfessionServiceRequest) GetStylistId() int32 {
	if m != nil {
		return m.StylistId
	}
	return 0
}

func init() {
	proto.RegisterType((*ProfessionService)(nil), "professionService.professionService")
	proto.RegisterType((*ProfessionServiceRequest)(nil), "professionService.professionServiceRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HarryStylistProfessionService service

type HarryStylistProfessionServiceClient interface {
	GetprofessionService(ctx context.Context, in *ProfessionServiceRequest, opts ...grpc.CallOption) (*ProfessionService, error)
	CreateprofessionService(ctx context.Context, in *ProfessionService, opts ...grpc.CallOption) (*ProfessionService, error)
	UpdateprofessionService(ctx context.Context, in *ProfessionService, opts ...grpc.CallOption) (*ProfessionService, error)
}

type harryStylistProfessionServiceClient struct {
	cc *grpc.ClientConn
}

func NewHarryStylistProfessionServiceClient(cc *grpc.ClientConn) HarryStylistProfessionServiceClient {
	return &harryStylistProfessionServiceClient{cc}
}

func (c *harryStylistProfessionServiceClient) GetprofessionService(ctx context.Context, in *ProfessionServiceRequest, opts ...grpc.CallOption) (*ProfessionService, error) {
	out := new(ProfessionService)
	err := grpc.Invoke(ctx, "/professionService.HarryStylistProfessionService/GetprofessionService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harryStylistProfessionServiceClient) CreateprofessionService(ctx context.Context, in *ProfessionService, opts ...grpc.CallOption) (*ProfessionService, error) {
	out := new(ProfessionService)
	err := grpc.Invoke(ctx, "/professionService.HarryStylistProfessionService/CreateprofessionService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harryStylistProfessionServiceClient) UpdateprofessionService(ctx context.Context, in *ProfessionService, opts ...grpc.CallOption) (*ProfessionService, error) {
	out := new(ProfessionService)
	err := grpc.Invoke(ctx, "/professionService.HarryStylistProfessionService/UpdateprofessionService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HarryStylistProfessionService service

type HarryStylistProfessionServiceServer interface {
	GetprofessionService(context.Context, *ProfessionServiceRequest) (*ProfessionService, error)
	CreateprofessionService(context.Context, *ProfessionService) (*ProfessionService, error)
	UpdateprofessionService(context.Context, *ProfessionService) (*ProfessionService, error)
}

func RegisterHarryStylistProfessionServiceServer(s *grpc.Server, srv HarryStylistProfessionServiceServer) {
	s.RegisterService(&_HarryStylistProfessionService_serviceDesc, srv)
}

func _HarryStylistProfessionService_GetprofessionService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfessionServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarryStylistProfessionServiceServer).GetprofessionService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/professionService.HarryStylistProfessionService/GetprofessionService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarryStylistProfessionServiceServer).GetprofessionService(ctx, req.(*ProfessionServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarryStylistProfessionService_CreateprofessionService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfessionService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarryStylistProfessionServiceServer).CreateprofessionService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/professionService.HarryStylistProfessionService/CreateprofessionService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarryStylistProfessionServiceServer).CreateprofessionService(ctx, req.(*ProfessionService))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarryStylistProfessionService_UpdateprofessionService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfessionService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarryStylistProfessionServiceServer).UpdateprofessionService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/professionService.HarryStylistProfessionService/UpdateprofessionService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarryStylistProfessionServiceServer).UpdateprofessionService(ctx, req.(*ProfessionService))
	}
	return interceptor(ctx, in, info, handler)
}

var _HarryStylistProfessionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "professionService.HarryStylistProfessionService",
	HandlerType: (*HarryStylistProfessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetprofessionService",
			Handler:    _HarryStylistProfessionService_GetprofessionService_Handler,
		},
		{
			MethodName: "CreateprofessionService",
			Handler:    _HarryStylistProfessionService_CreateprofessionService_Handler,
		},
		{
			MethodName: "UpdateprofessionService",
			Handler:    _HarryStylistProfessionService_UpdateprofessionService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "professionService.proto",
}

func init() { proto.RegisterFile("professionService.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x49, 0xbe, 0xaf, 0xd5, 0x5c, 0xff, 0x80, 0x83, 0xd0, 0x10, 0x28, 0x86, 0xea, 0x22,
	0x20, 0x4c, 0xa1, 0x6e, 0x74, 0x29, 0x0a, 0xda, 0x9d, 0xa4, 0xba, 0x2e, 0xa9, 0x73, 0x5b, 0x06,
	0x52, 0x27, 0xce, 0x4c, 0x85, 0x3e, 0x8a, 0x6f, 0xe6, 0xe3, 0x48, 0x72, 0x53, 0x03, 0x9d, 0x82,
	0xd9, 0xb8, 0x3d, 0xf7, 0x77, 0xce, 0xcc, 0x3d, 0x17, 0x7a, 0x85, 0x56, 0x73, 0x34, 0x46, 0xaa,
	0xb7, 0x09, 0xea, 0x0f, 0xf9, 0x8a, 0xbc, 0xd0, 0xca, 0x2a, 0x76, 0xe2, 0x0c, 0xa2, 0xb3, 0x85,
	0x52, 0x8b, 0x1c, 0x87, 0x15, 0x30, 0x5b, 0xcd, 0x87, 0x56, 0x2e, 0xd1, 0xd8, 0x6c, 0x59, 0x90,
	0x67, 0xf0, 0xe9, 0x83, 0x6b, 0x63, 0xc7, 0xe0, 0x4b, 0x11, 0x7a, 0xb1, 0x97, 0x74, 0x52, 0x5f,
	0x0a, 0xd6, 0x07, 0x30, 0x76, 0x9d, 0x4b, 0x63, 0xa7, 0x52, 0x84, 0x7e, 0xa5, 0x07, 0xb5, 0x32,
	0x16, 0xec, 0x1c, 0x8e, 0x9a, 0x8c, 0x92, 0xf8, 0x57, 0x11, 0x87, 0x8d, 0x38, 0xa6, 0x0c, 0x8a,
	0x2f, 0x89, 0xff, 0x75, 0x06, 0x29, 0x34, 0x96, 0x66, 0x2a, 0x30, 0x47, 0x8b, 0x22, 0xec, 0xc4,
	0x5e, 0xb2, 0x9f, 0x06, 0xd2, 0xdc, 0x93, 0xc0, 0xae, 0x21, 0x78, 0x29, 0x44, 0x66, 0x51, 0xdc,
	0xda, 0xb0, 0x1b, 0x7b, 0xc9, 0xc1, 0x28, 0xe2, 0xb4, 0x1c, 0xdf, 0x2c, 0xc7, 0x9f, 0x37, 0xcb,
	0xa5, 0x0d, 0x5c, 0x3a, 0xef, 0x34, 0xd6, 0xce, 0xbd, 0xdf, 0x9d, 0x3f, 0xf0, 0xe0, 0x06, 0x42,
	0xa7, 0x9a, 0x14, 0xdf, 0x57, 0x68, 0xec, 0x56, 0x23, 0xde, 0x56, 0x23, 0xa3, 0x2f, 0x1f, 0xfa,
	0x8f, 0x99, 0xd6, 0xeb, 0x09, 0x49, 0x4f, 0x4e, 0xc5, 0x12, 0x4e, 0x1f, 0xd0, 0xba, 0xd5, 0x5f,
	0xf2, 0x9d, 0xe7, 0xdd, 0xf9, 0x8b, 0xe8, 0xa2, 0x0d, 0xcc, 0x10, 0x7a, 0xb4, 0x94, 0x3b, 0x6a,
	0x15, 0xd0, 0xfe, 0x19, 0x6a, 0xfd, 0x4f, 0x9f, 0x99, 0x75, 0xab, 0xa3, 0x5d, 0x7d, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x5b, 0x8c, 0xc7, 0xc8, 0x07, 0x03, 0x00, 0x00,
}
