// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service/service.proto

It has these top-level messages:
	Service
	ServiceRequest
	ServiceDeleteResponse
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service struct {
	Id           int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	IsActive     bool                       `protobuf:"varint,3,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	ProfessionId int32                      `protobuf:"varint,4,opt,name=profession_id,json=professionId" json:"profession_id,omitempty"`
	UpdatedAt    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt    *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	DeletedAt    *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=DeletedAt" json:"DeletedAt,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Service) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Service) GetProfessionId() int32 {
	if m != nil {
		return m.ProfessionId
	}
	return 0
}

func (m *Service) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Service) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Service) GetDeletedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type ServiceRequest struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ServiceRequest) Reset()                    { *m = ServiceRequest{} }
func (m *ServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceRequest) ProtoMessage()               {}
func (*ServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ServiceDeleteResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Code   int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (m *ServiceDeleteResponse) Reset()                    { *m = ServiceDeleteResponse{} }
func (m *ServiceDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceDeleteResponse) ProtoMessage()               {}
func (*ServiceDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceDeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ServiceDeleteResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Service)(nil), "service.Service")
	proto.RegisterType((*ServiceRequest)(nil), "service.serviceRequest")
	proto.RegisterType((*ServiceDeleteResponse)(nil), "service.serviceDeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HarryServiceService service

type HarryServiceServiceClient interface {
	GetService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*Service, error)
	GetAllService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (HarryServiceService_GetAllServiceClient, error)
	CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error)
	UpdateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error)
	DeleteService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*ServiceDeleteResponse, error)
}

type harryServiceServiceClient struct {
	cc *grpc.ClientConn
}

func NewHarryServiceServiceClient(cc *grpc.ClientConn) HarryServiceServiceClient {
	return &harryServiceServiceClient{cc}
}

func (c *harryServiceServiceClient) GetService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/service.HarryServiceService/GetService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harryServiceServiceClient) GetAllService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (HarryServiceService_GetAllServiceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_HarryServiceService_serviceDesc.Streams[0], c.cc, "/service.HarryServiceService/GetAllService", opts...)
	if err != nil {
		return nil, err
	}
	x := &harryServiceServiceGetAllServiceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HarryServiceService_GetAllServiceClient interface {
	Recv() (*Service, error)
	grpc.ClientStream
}

type harryServiceServiceGetAllServiceClient struct {
	grpc.ClientStream
}

func (x *harryServiceServiceGetAllServiceClient) Recv() (*Service, error) {
	m := new(Service)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *harryServiceServiceClient) CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/service.HarryServiceService/CreateService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harryServiceServiceClient) UpdateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/service.HarryServiceService/UpdateService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harryServiceServiceClient) DeleteService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*ServiceDeleteResponse, error) {
	out := new(ServiceDeleteResponse)
	err := grpc.Invoke(ctx, "/service.HarryServiceService/DeleteService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HarryServiceService service

type HarryServiceServiceServer interface {
	GetService(context.Context, *ServiceRequest) (*Service, error)
	GetAllService(*ServiceRequest, HarryServiceService_GetAllServiceServer) error
	CreateService(context.Context, *Service) (*Service, error)
	UpdateService(context.Context, *Service) (*Service, error)
	DeleteService(context.Context, *Service) (*ServiceDeleteResponse, error)
}

func RegisterHarryServiceServiceServer(s *grpc.Server, srv HarryServiceServiceServer) {
	s.RegisterService(&_HarryServiceService_serviceDesc, srv)
}

func _HarryServiceService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarryServiceServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.HarryServiceService/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarryServiceServiceServer).GetService(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarryServiceService_GetAllService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HarryServiceServiceServer).GetAllService(m, &harryServiceServiceGetAllServiceServer{stream})
}

type HarryServiceService_GetAllServiceServer interface {
	Send(*Service) error
	grpc.ServerStream
}

type harryServiceServiceGetAllServiceServer struct {
	grpc.ServerStream
}

func (x *harryServiceServiceGetAllServiceServer) Send(m *Service) error {
	return x.ServerStream.SendMsg(m)
}

func _HarryServiceService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarryServiceServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.HarryServiceService/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarryServiceServiceServer).CreateService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarryServiceService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarryServiceServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.HarryServiceService/UpdateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarryServiceServiceServer).UpdateService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarryServiceService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarryServiceServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.HarryServiceService/DeleteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarryServiceServiceServer).DeleteService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

var _HarryServiceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.HarryServiceService",
	HandlerType: (*HarryServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetService",
			Handler:    _HarryServiceService_GetService_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _HarryServiceService_CreateService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _HarryServiceService_UpdateService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _HarryServiceService_DeleteService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllService",
			Handler:       _HarryServiceService_GetAllService_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service/service.proto",
}

func init() { proto.RegisterFile("service/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0xb0, 0x6d, 0x37, 0x03, 0x59, 0x21, 0x23, 0x20, 0x2a, 0x12, 0x44, 0xe5, 0x92,
	0x53, 0x82, 0xb6, 0x48, 0x80, 0xe0, 0x12, 0x16, 0x69, 0xe1, 0x6a, 0xe0, 0xc2, 0x65, 0xe5, 0xc6,
	0xb3, 0x5d, 0x4b, 0x71, 0x1d, 0x62, 0x67, 0xa5, 0x3e, 0x0c, 0x0f, 0xc2, 0xdb, 0xa1, 0xd8, 0x71,
	0xaa, 0xf2, 0x47, 0xa5, 0x27, 0x7b, 0x3c, 0xdf, 0x6f, 0x32, 0xfa, 0x3e, 0x05, 0x1e, 0x6a, 0x6c,
	0x6f, 0x45, 0x85, 0xc5, 0x70, 0xe6, 0x4d, 0xab, 0x8c, 0x22, 0xb3, 0xa1, 0x9c, 0x3f, 0x5b, 0x2b,
	0xb5, 0xae, 0xb1, 0xb0, 0xcf, 0xab, 0xee, 0xba, 0x30, 0x42, 0xa2, 0x36, 0x4c, 0x36, 0x4e, 0xb9,
	0xf8, 0x11, 0xc2, 0xec, 0xb3, 0x13, 0x93, 0x33, 0x08, 0x05, 0x4f, 0x82, 0x34, 0xc8, 0x26, 0x34,
	0x14, 0x9c, 0x10, 0x38, 0xd9, 0x30, 0x89, 0x49, 0x98, 0x06, 0x59, 0x44, 0xed, 0x9d, 0x3c, 0x81,
	0x48, 0xe8, 0x2b, 0x56, 0x19, 0x71, 0x8b, 0xc9, 0x9d, 0x34, 0xc8, 0x4e, 0xe9, 0xa9, 0xd0, 0xa5,
	0xad, 0xc9, 0x73, 0x88, 0x9b, 0x56, 0x5d, 0xa3, 0xd6, 0x42, 0x6d, 0xae, 0x04, 0x4f, 0x4e, 0xec,
	0xac, 0x7b, 0xbb, 0xc7, 0x4f, 0x9c, 0xbc, 0x86, 0xe8, 0x6b, 0xc3, 0x99, 0x41, 0x5e, 0x9a, 0x64,
	0x92, 0x06, 0xd9, 0xdd, 0xf3, 0x79, 0xee, 0xd6, 0xcc, 0xfd, 0x9a, 0xf9, 0x17, 0xbf, 0x26, 0xdd,
	0x89, 0x7b, 0xf2, 0xa2, 0xc5, 0x81, 0x9c, 0x1e, 0x26, 0x47, 0x71, 0x4f, 0x7e, 0xc0, 0x1a, 0x1d,
	0x39, 0x3b, 0x4c, 0x8e, 0xe2, 0xc5, 0x4b, 0x38, 0x1b, 0xbc, 0xa4, 0xf8, 0xbd, 0x43, 0x6d, 0xfe,
	0xc7, 0xa5, 0xc5, 0xc5, 0x18, 0x8c, 0x9b, 0x44, 0x51, 0x37, 0x6a, 0xa3, 0x91, 0x3c, 0x82, 0xa9,
	0x36, 0xcc, 0x74, 0xda, 0x0e, 0x88, 0xe8, 0x50, 0xf5, 0x43, 0x2a, 0xc5, 0xdd, 0x90, 0x09, 0xb5,
	0xf7, 0xf3, 0x9f, 0x21, 0x3c, 0xf8, 0xc8, 0xda, 0x76, 0x3b, 0xe4, 0xe3, 0x63, 0x7a, 0x05, 0x70,
	0x89, 0xc6, 0x57, 0x8f, 0x73, 0x1f, 0xfd, 0xfe, 0x9e, 0xf3, 0xfb, 0x63, 0xc3, 0x4b, 0xdf, 0x41,
	0x7c, 0x89, 0xa6, 0xac, 0xeb, 0xe3, 0xd9, 0x17, 0x01, 0x59, 0x42, 0xec, 0x0c, 0xf5, 0xf4, 0x1f,
	0xa2, 0xbf, 0x7c, 0x72, 0x09, 0xb1, 0xcb, 0xef, 0x18, 0xa8, 0x84, 0xd8, 0xd9, 0xf6, 0x6f, 0xe8,
	0xe9, 0xef, 0x9b, 0xef, 0xfb, 0xfc, 0xfe, 0xed, 0xb7, 0x37, 0x6b, 0x61, 0x6e, 0xba, 0x55, 0x5e,
	0x29, 0x59, 0x30, 0xa3, 0xa4, 0xde, 0x6a, 0x83, 0x52, 0x1b, 0x64, 0xb2, 0xb8, 0xe9, 0x5d, 0xb5,
	0xb9, 0x4b, 0xc5, 0xb1, 0xd6, 0x85, 0x3d, 0xfc, 0x3f, 0xb4, 0x9a, 0xda, 0xd6, 0xf2, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x7e, 0xb9, 0x46, 0xff, 0x5d, 0x03, 0x00, 0x00,
}
